Descripción
Aplicarás lo aprendido sobre APIs REST, métodos HTTP y códigos de estado, utilizando APIs públicas para consultar datos, filtrarlos y finalmente guardarlos en un DataFrame de pandas.

Recursos:

Nivel 1:
{JSON} Placeholder

Nivel 2:
Try Public APIs for free

Nivel 3:
Open Data BCN

----------------------------------------------------------------------------------------------------------------------

Nivel 1

Desde un Jupyter Notebook realizarás los siguientes ejercicios utilizando la librería requests de Python.

Exploración básica con una API de laboratorio.

-----------------------------------------------------------------------------------------------------------------

1. Consulta la API pública JSONPlaceholder utilizando el método GET para obtener:

* Lista de publicaciones (/posts)
* Lista de usuarios (/users)
* Lista de tareas (/todos)

In [2]:
import pandas as pd
import requests

In [3]:
url_base = "https://jsonplaceholder.typicode.com"

In [4]:
a = requests.get(url_base + "/posts")
posts = a.json()

b = requests.get(url_base + "/users")
users = b.json()

c = requests.get(url_base + "/todos")
todos = c.json()

posts

[{'userId': 1,
  'id': 1,
  'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
  'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'},
 {'userId': 1,
  'id': 2,
  'title': 'qui est esse',
  'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'},
 {'userId': 1,
  'id': 3,
  'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
  'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'},
 {'userId': 1,
  'id': 4,
  'title': 'eum et est occaecati',
  'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'},
 {'userId': 1,
  'id': 5,
  'title': 'nesciunt quas odio',
  'body': 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque'},
 {'userId': 1,
  'id': 6,
  'title': 'dolorem eum magni eos aperiam quia',
  'body': 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae'},
 {'userId': 1,
  'id': 7,
  'title': 'magnam facilis autem',
  'body': 'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas'},
 {'userId': 1,
  'id': 8,
  'title': 'dolorem dolore est ipsam',
  'body': 'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae'},
 {'userId': 1,
  'id': 9,
  'title': 'nesciunt iure omnis dolorem tempora et accusantium',
  'body': 'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas'},
 {'userId': 1,
  'id': 10,
  'title': 'optio molestias id quia eum',
  'body': 'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error'},
 {'userId': 2,
  'id': 11,
  'title': 'et ea vero quia laudantium autem',
  'body': 'delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi'},
 {'userId': 2,
  'id': 12,
  'title': 'in quibusdam tempore odit est dolorem',
  'body': 'itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio'},
 {'userId': 2,
  'id': 13,
  'title': 'dolorum ut in voluptas mollitia et saepe quo animi',
  'body': 'aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam'},
 {'userId': 2,
  'id': 14,
  'title': 'voluptatem eligendi optio',
  'body': 'fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum'},
 {'userId': 2,
  'id': 15,
  'title': 'eveniet quod temporibus',
  'body': 'reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae'},
 {'userId': 2,
  'id': 16,
  'title': 'sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio',
  'body': 'suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta'},
 {'userId': 2,
  'id': 17,
  'title': 'fugit voluptas sed molestias voluptatem provident',
  'body': 'eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo'},
 {'userId': 2,
  'id': 18,
  'title': 'voluptate et itaque vero tempora molestiae',
  'body': 'eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam'},
 {'userId': 2,
  'id': 19,
  'title': 'adipisci placeat illum aut reiciendis qui',
  'body': 'illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas'},
 {'userId': 2,
  'id': 20,
  'title': 'doloribus ad provident suscipit at',
  'body': 'qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo'},
 {'userId': 3,
  'id': 21,
  'title': 'asperiores ea ipsam voluptatibus modi minima quia sint',
  'body': 'repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt'},
 {'userId': 3,
  'id': 22,
  'title': 'dolor sint quo a velit explicabo quia nam',
  'body': 'eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse'},
 {'userId': 3,
  'id': 23,
  'title': 'maxime id vitae nihil numquam',
  'body': 'veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis'},
 {'userId': 3,
  'id': 24,
  'title': 'autem hic labore sunt dolores incidunt',
  'body': 'enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt'},
 {'userId': 3,
  'id': 25,
  'title': 'rem alias distinctio quo quis',
  'body': 'ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio'},
 {'userId': 3,
  'id': 26,
  'title': 'est et quae odit qui non',
  'body': 'similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero'},
 {'userId': 3,
  'id': 27,
  'title': 'quasi id et eos tenetur aut quo autem',
  'body': 'eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur'},
 {'userId': 3,
  'id': 28,
  'title': 'delectus ullam et corporis nulla voluptas sequi',
  'body': 'non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum'},
 {'userId': 3,
  'id': 29,
  'title': 'iusto eius quod necessitatibus culpa ea',
  'body': 'odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores'},
 {'userId': 3,
  'id': 30,
  'title': 'a quo magni similique perferendis',
  'body': 'alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia'},
 {'userId': 4,
  'id': 31,
  'title': 'ullam ut quidem id aut vel consequuntur',
  'body': 'debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae'},
 {'userId': 4,
  'id': 32,
  'title': 'doloremque illum aliquid sunt',
  'body': 'deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime'},
 {'userId': 4,
  'id': 33,
  'title': 'qui explicabo molestiae dolorem',
  'body': 'rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod'},
 {'userId': 4,
  'id': 34,
  'title': 'magnam ut rerum iure',
  'body': 'ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis'},
 {'userId': 4,
  'id': 35,
  'title': 'id nihil consequatur molestias animi provident',
  'body': 'nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit'},
 {'userId': 4,
  'id': 36,
  'title': 'fuga nam accusamus voluptas reiciendis itaque',
  'body': 'ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore'},
 {'userId': 4,
  'id': 37,
  'title': 'provident vel ut sit ratione est',
  'body': 'debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui'},
 {'userId': 4,
  'id': 38,
  'title': 'explicabo et eos deleniti nostrum ab id repellendus',
  'body': 'animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure'},
 {'userId': 4,
  'id': 39,
  'title': 'eos dolorem iste accusantium est eaque quam',
  'body': 'corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex'},
 {'userId': 4,
  'id': 40,
  'title': 'enim quo cumque',
  'body': 'ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam'},
 {'userId': 5,
  'id': 41,
  'title': 'non est facere',
  'body': 'molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe'},
 {'userId': 5,
  'id': 42,
  'title': 'commodi ullam sint et excepturi error explicabo praesentium voluptas',
  'body': 'odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut'},
 {'userId': 5,
  'id': 43,
  'title': 'eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis',
  'body': 'similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis'},
 {'userId': 5,
  'id': 44,
  'title': 'optio dolor molestias sit',
  'body': 'temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae'},
 {'userId': 5,
  'id': 45,
  'title': 'ut numquam possimus omnis eius suscipit laudantium iure',
  'body': 'est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem'},
 {'userId': 5,
  'id': 46,
  'title': 'aut quo modi neque nostrum ducimus',
  'body': 'voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid'},
 {'userId': 5,
  'id': 47,
  'title': 'quibusdam cumque rem aut deserunt',
  'body': 'voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate'},
 {'userId': 5,
  'id': 48,
  'title': 'ut voluptatem illum ea doloribus itaque eos',
  'body': 'voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit'},
 {'userId': 5,
  'id': 49,
  'title': 'laborum non sunt aut ut assumenda perspiciatis voluptas',
  'body': 'inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut'},
 {'userId': 5,
  'id': 50,
  'title': 'repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem',
  'body': 'error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur'},
 {'userId': 6,
  'id': 51,
  'title': 'soluta aliquam aperiam consequatur illo quis voluptas',
  'body': 'sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem'},
 {'userId': 6,
  'id': 52,
  'title': 'qui enim et consequuntur quia animi quis voluptate quibusdam',
  'body': 'iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum'},
 {'userId': 6,
  'id': 53,
  'title': 'ut quo aut ducimus alias',
  'body': 'minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique'},
 {'userId': 6,
  'id': 54,
  'title': 'sit asperiores ipsam eveniet odio non quia',
  'body': 'totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia'},
 {'userId': 6,
  'id': 55,
  'title': 'sit vel voluptatem et non libero',
  'body': 'debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit'},
 {'userId': 6,
  'id': 56,
  'title': 'qui et at rerum necessitatibus',
  'body': 'aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi'},
 {'userId': 6,
  'id': 57,
  'title': 'sed ab est est',
  'body': 'at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est'},
 {'userId': 6,
  'id': 58,
  'title': 'voluptatum itaque dolores nisi et quasi',
  'body': 'veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam'},
 {'userId': 6,
  'id': 59,
  'title': 'qui commodi dolor at maiores et quis id accusantium',
  'body': 'perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt'},
 {'userId': 6,
  'id': 60,
  'title': 'consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere',
  'body': 'asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis'},
 {'userId': 7,
  'id': 61,
  'title': 'voluptatem doloribus consectetur est ut ducimus',
  'body': 'ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit'},
 {'userId': 7,
  'id': 62,
  'title': 'beatae enim quia vel',
  'body': 'enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio'},
 {'userId': 7,
  'id': 63,
  'title': 'voluptas blanditiis repellendus animi ducimus error sapiente et suscipit',
  'body': 'enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta'},
 {'userId': 7,
  'id': 64,
  'title': 'et fugit quas eum in in aperiam quod',
  'body': 'id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui'},
 {'userId': 7,
  'id': 65,
  'title': 'consequatur id enim sunt et et',
  'body': 'voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur'},
 {'userId': 7,
  'id': 66,
  'title': 'repudiandae ea animi iusto',
  'body': 'officia veritatis tenetur vero qui itaque\nsint non ratione\nsed et ut asperiores iusto eos molestiae nostrum\nveritatis quibusdam et nemo iusto saepe'},
 {'userId': 7,
  'id': 67,
  'title': 'aliquid eos sed fuga est maxime repellendus',
  'body': 'reprehenderit id nostrum\nvoluptas doloremque pariatur sint et accusantium quia quod aspernatur\net fugiat amet\nnon sapiente et consequatur necessitatibus molestiae'},
 {'userId': 7,
  'id': 68,
  'title': 'odio quis facere architecto reiciendis optio',
  'body': 'magnam molestiae perferendis quisquam\nqui cum reiciendis\nquaerat animi amet hic inventore\nea quia deleniti quidem saepe porro velit'},
 {'userId': 7,
  'id': 69,
  'title': 'fugiat quod pariatur odit minima',
  'body': 'officiis error culpa consequatur modi asperiores et\ndolorum assumenda voluptas et vel qui aut vel rerum\nvoluptatum quisquam perspiciatis quia rerum consequatur totam quas\nsequi commodi repudiandae asperiores et saepe a'},
 {'userId': 7,
  'id': 70,
  'title': 'voluptatem laborum magni',
  'body': 'sunt repellendus quae\nest asperiores aut deleniti esse accusamus repellendus quia aut\nquia dolorem unde\neum tempora esse dolore'},
 {'userId': 8,
  'id': 71,
  'title': 'et iusto veniam et illum aut fuga',
  'body': 'occaecati a doloribus\niste saepe consectetur placeat eum voluptate dolorem et\nqui quo quia voluptas\nrerum ut id enim velit est perferendis'},
 {'userId': 8,
  'id': 72,
  'title': 'sint hic doloribus consequatur eos non id',
  'body': 'quam occaecati qui deleniti consectetur\nconsequatur aut facere quas exercitationem aliquam hic voluptas\nneque id sunt ut aut accusamus\nsunt consectetur expedita inventore velit'},
 {'userId': 8,
  'id': 73,
  'title': 'consequuntur deleniti eos quia temporibus ab aliquid at',
  'body': 'voluptatem cumque tenetur consequatur expedita ipsum nemo quia explicabo\naut eum minima consequatur\ntempore cumque quae est et\net in consequuntur voluptatem voluptates aut'},
 {'userId': 8,
  'id': 74,
  'title': 'enim unde ratione doloribus quas enim ut sit sapiente',
  'body': 'odit qui et et necessitatibus sint veniam\nmollitia amet doloremque molestiae commodi similique magnam et quam\nblanditiis est itaque\nquo et tenetur ratione occaecati molestiae tempora'},
 {'userId': 8,
  'id': 75,
  'title': 'dignissimos eum dolor ut enim et delectus in',
  'body': 'commodi non non omnis et voluptas sit\nautem aut nobis magnam et sapiente voluptatem\net laborum repellat qui delectus facilis temporibus\nrerum amet et nemo voluptate expedita adipisci error dolorem'},
 {'userId': 8,
  'id': 76,
  'title': 'doloremque officiis ad et non perferendis',
  'body': 'ut animi facere\ntotam iusto tempore\nmolestiae eum aut et dolorem aperiam\nquaerat recusandae totam odio'},
 {'userId': 8,
  'id': 77,
  'title': 'necessitatibus quasi exercitationem odio',

In [5]:
df_posts = pd.DataFrame(posts)
df_users = pd.DataFrame(users)
df_todos = pd.DataFrame(todos)

df_posts

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

---------------------------------------

2. Muestra por pantalla:

* La cantidad total de cada recurso.
* El código de estado de cada petición.

In [6]:
print("RECURSO | TOTAL | STATUS CODE")
print("-" * 35)
print(f"Posts   | {len(posts)} | {a.status_code}")
print(f"Users   | {len(users)}  | {b.status_code}")
print(f"Todos   | {len(todos)} | {c.status_code}")

RECURSO | TOTAL | STATUS CODE
-----------------------------------
Posts   | 100 | 200
Users   | 10  | 200
Todos   | 200 | 200

----------------------

3. Realiza una petición a una publicación inexistente para obtener un error 404 y muestra el código de estado recibido.

In [7]:
invalid_post_response = requests.get(f"{url_base}/posts/101")

print("\nPetición a publicación inexistente:")
print("Status code:", invalid_post_response.status_code)

Petición a publicación inexistente:
Status code: 404

------------------------

4. Realiza una petición POST para crear una nueva publicación ficticia. Incluye el título, el cuerpo del mensaje y un userId.

* Muestra la respuesta JSON.
* Muestra el código de estado.

In [8]:
new_post = {
    "userId": 101,
    "id": 101,
    "title": "Nueva Publicación",
    "body": "Contenido de la publicación",   
}

In [9]:
post_response = requests.post(f"{url_base}/posts", json=new_post)

print("\nPOST - Crear publicación:")
print("Respuesta JSON:", post_response.json())
print("Status code:", post_response.status_code)

POST - Crear publicación:
Respuesta JSON: {'userId': 101, 'id': 101, 'title': 'Nueva Publicación', 'body': 'Contenido de la publicación'}
Status code: 201

----------

5. Realiza una petición PATCH para modificar parcialmente una publicación existente.

* Muestra la respuesta JSON.
* Muestra el código de estado.

In [10]:
patch_data = {
    "title": "Título actualizado"
}

patch_response = requests.patch(f"{url_base}/posts/1", json=patch_data)

print("\nPATCH - Modificar publicación:")
print("Respuesta JSON:", patch_response.json())
print("Status code:", patch_response.status_code)

PATCH - Modificar publicación:
Respuesta JSON: {'userId': 1, 'id': 1, 'title': 'Título actualizado', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
Status code: 200

-------------

6. Haz una petición DELETE sobre una publicación.

* Muestra la respuesta JSON.
* Muestra el código de estado.

In [11]:
delete_response = requests.delete(f"{url_base}/posts/1")

print("\nDELETE - Eliminar publicación:")
print("Respuesta JSON:", delete_response.json())
print("Status code:", delete_response.status_code)

DELETE - Eliminar publicación:
Respuesta JSON: {}
Status code: 200

-----------------

Nivel 2.

Interacción con una API pública real

-----------------

1. Explora el repositorio de Public APIs y elige una API que permita realizar peticiones GET.

La API REST Countries devuelve las respuestas en formato JSON,
lo que permite su fácil manipulación y conversión a estructuras
como diccionarios de Python y DataFrames de pandas.

------------

2. Lee la documentación de la API:

* Revisa la sección de endpoints disponibles. En un markdown, apunta al menos dos endpoints diferentes.
* Comprueba si ofrece filtros o parámetros opcionales interesantes. En un markdown, anótalos.
* Verifica que la respuesta sea en formato JSON (es el más adecuado para este ejercicio).

- GET /v3.1/independent
  Devuelve países independientes o no independientes.
    Parámetro opcional:
  - status=true | false

    - status (endpoint /independent):
    Permite filtrar países independientes o no independientes.
    Ejemplo:
    ?status=true


- GET /v3.1/all
  Devuelve todos los países.
  Es obligatorio usar el parámetro 'fields'.

  - fields:
  Permite seleccionar solo los campos necesarios en la respuesta.
  Ejemplo:
  ?fields=name,capital,population,region

- GET /v3.1/name/{name}
  Busca países por nombre común u oficial.

- GET /v3.1/region/{region}
  Devuelve países filtrados por región (Europe, Asia, Americas, etc.).

- GET /v3.1/capital/{capital}
  Busca países por ciudad capital.

---------------

3. Haz una petición GET sencilla:

* Muestra el código de estado de la respuesta.
* Imprime de forma clara algunos de los campos de la respuesta JSON.

In [12]:
url_base2 = "https://restcountries.com/v3.1/all?fields=name,flags`"

---------------------------

In [13]:
params = {
    "fields": "cca3,name,currencies,languages,capital,region"
}

response = requests.get(url_base2, params=params)

print("Status code:", response.status_code)

Status code: 200

In [14]:
world_data = response.json()

world_data

[{'name': {'common': 'Andorra',
   'official': 'Principality of Andorra',
   'nativeName': {'cat': {'official': "Principat d'Andorra",
     'common': 'Andorra'}}},
  'cca3': 'AND',
  'currencies': {'EUR': {'name': 'Euro', 'symbol': '€'}},
  'capital': ['Andorra la Vella'],
  'region': 'Europe',
  'languages': {'cat': 'Catalan'}},
 {'name': {'common': 'Trinidad and Tobago',
   'official': 'Republic of Trinidad and Tobago',
   'nativeName': {'eng': {'official': 'Republic of Trinidad and Tobago',
     'common': 'Trinidad and Tobago'}}},
  'cca3': 'TTO',
  'currencies': {'TTD': {'name': 'Trinidad and Tobago dollar', 'symbol': '$'}},
  'capital': ['Port of Spain'],
  'region': 'Americas',
  'languages': {'eng': 'English'}},
 {'name': {'common': 'Serbia',
   'official': 'Republic of Serbia',
   'nativeName': {'srp': {'official': 'Република Србија',
     'common': 'Србија'}}},
  'cca3': 'SRB',
  'currencies': {'RSD': {'name': 'Serbian dinar', 'symbol': 'дин.'}},
  'capital': ['Belgrade'],
  'region': 'Europe',
  'languages': {'srp': 'Serbian'}},
 {'name': {'common': 'United Kingdom',
   'official': 'United Kingdom of Great Britain and Northern Ireland',
   'nativeName': {'eng': {'official': 'United Kingdom of Great Britain and Northern Ireland',
     'common': 'United Kingdom'}}},
  'cca3': 'GBR',
  'currencies': {'GBP': {'name': 'British pound', 'symbol': '£'}},
  'capital': ['London'],
  'region': 'Europe',
  'languages': {'eng': 'English'}},
 {'name': {'common': 'Russia',
   'official': 'Russian Federation',
   'nativeName': {'rus': {'official': 'Российская Федерация',
     'common': 'Россия'}}},
  'cca3': 'RUS',
  'currencies': {'RUB': {'name': 'Russian ruble', 'symbol': '₽'}},
  'capital': ['Moscow'],
  'region': 'Europe',
  'languages': {'rus': 'Russian'}},
 {'name': {'common': 'Hong Kong',
   'official': "Hong Kong Special Administrative Region of the People's Republic of China",
   'nativeName': {'eng': {'official': "Hong Kong Special Administrative Region of the People's Republic of China",
     'common': 'Hong Kong'},
    'zho': {'official': '中华人民共和国香港特别行政区', 'common': '香港'}}},
  'cca3': 'HKG',
  'currencies': {'HKD': {'name': 'Hong Kong dollar', 'symbol': '$'}},
  'capital': ['City of Victoria'],
  'region': 'Asia',
  'languages': {'eng': 'English', 'zho': 'Chinese'}},
 {'name': {'common': 'Western Sahara',
   'official': 'Sahrawi Arab Democratic Republic',
   'nativeName': {'ber': {'official': 'Sahrawi Arab Democratic Republic',
     'common': 'Western Sahara'},
    'mey': {'official': 'الجمهورية العربية الصحراوية الديمقراطية',
     'common': 'الصحراء الغربية'},
    'spa': {'official': 'República Árabe Saharaui Democrática',
     'common': 'Sahara Occidental'}}},
  'cca3': 'ESH',
  'currencies': {'DZD': {'name': 'Algerian dinar', 'symbol': 'دج'},
   'MAD': {'name': 'Moroccan dirham', 'symbol': 'DH'},
   'MRU': {'name': 'Mauritanian ouguiya', 'symbol': 'UM'}},
  'capital': ['El Aaiún'],
  'region': 'Africa',
  'languages': {'ber': 'Berber', 'mey': 'Hassaniya', 'spa': 'Spanish'}},
 {'name': {'common': 'Uruguay',
   'official': 'Oriental Republic of Uruguay',
   'nativeName': {'spa': {'official': 'República Oriental del Uruguay',
     'common': 'Uruguay'}}},
  'cca3': 'URY',
  'currencies': {'UYU': {'name': 'Uruguayan peso', 'symbol': '$'}},
  'capital': ['Montevideo'],
  'region': 'Americas',
  'languages': {'spa': 'Spanish'}},
 {'name': {'common': 'Barbados',
   'official': 'Barbados',
   'nativeName': {'eng': {'official': 'Barbados', 'common': 'Barbados'}}},
  'cca3': 'BRB',
  'currencies': {'BBD': {'name': 'Barbadian dollar', 'symbol': '$'}},
  'capital': ['Bridgetown'],
  'region': 'Americas',
  'languages': {'eng': 'English'}},
 {'name': {'common': 'Palestine',
   'official': 'State of Palestine',
   'nativeName': {'ara': {'official': 'دولة فلسطين', 'common': 'فلسطين'}}},
  'cca3': 'PSE',
  'currencies': {'EGP': {'name': 'Egyptian pound', 'symbol': 'E£'},
   'ILS': {'name': 'Israeli new shekel', 'symbol': '₪'},
   'JOD': {'name': 'Jordanian dinar', 'symbol': 'JD'}},
  'capital': ['Ramallah', 'Jerusalem'],
  'region': 'Asia',
  'languages': {'ara': 'Arabic'}},
 {'name': {'common': 'Mexico',
   'official': 'United Mexican States',
   'nativeName': {'spa': {'official': 'Estados Unidos Mexicanos',
     'common': 'México'}}},
  'cca3': 'MEX',
  'currencies': {'MXN': {'name': 'Mexican peso', 'symbol': '$'}},
  'capital': ['Mexico City'],
  'region': 'Americas',
  'languages': {'spa': 'Spanish'}},
 {'name': {'common': 'Malawi',
   'official': 'Republic of Malawi',
   'nativeName': {'eng': {'official': 'Republic of Malawi',
     'common': 'Malawi'},
    'nya': {'official': 'Chalo cha Malawi, Dziko la Malaŵi',
     'common': 'Malaŵi'}}},
  'cca3': 'MWI',
  'currencies': {'MWK': {'name': 'Malawian kwacha', 'symbol': 'MK'}},
  'capital': ['Lilongwe'],
  'region': 'Africa',
  'languages': {'eng': 'English', 'nya': 'Chewa'}},
 {'name': {'common': 'Antarctica', 'official': 'Antarctica', 'nativeName': {}},
  'cca3': 'ATA',
  'currencies': {},
  'capital': [],
  'region': 'Antarctic',
  'languages': {}},
 {'name': {'common': 'New Caledonia',
   'official': 'New Caledonia',
   'nativeName': {'fra': {'official': 'Nouvelle-Calédonie',
     'common': 'Nouvelle-Calédonie'}}},
  'cca3': 'NCL',
  'currencies': {'XPF': {'name': 'CFP franc', 'symbol': '₣'}},
  'capital': ['Nouméa'],
  'region': 'Oceania',
  'languages': {'fra': 'French'}},
 {'name': {'common': 'Svalbard and Jan Mayen',
   'official': 'Svalbard og Jan Mayen',
   'nativeName': {'nor': {'official': 'Svalbard og Jan Mayen',
     'common': 'Svalbard og Jan Mayen'}}},
  'cca3': 'SJM',
  'currencies': {'NOK': {'name': 'krone', 'symbol': 'kr'}},
  'capital': ['Longyearbyen'],
  'region': 'Europe',
  'languages': {'nor': 'Norwegian'}},
 {'name': {'common': 'Norfolk Island',
   'official': 'Territory of Norfolk Island',
   'nativeName': {'eng': {'official': 'Territory of Norfolk Island',
     'common': 'Norfolk Island'},
    'pih': {'official': "Teratri of Norf'k Ailen", 'common': "Norf'k Ailen"}}},
  'cca3': 'NFK',
  'currencies': {'AUD': {'name': 'Australian dollar', 'symbol': '$'}},
  'capital': ['Kingston'],
  'region': 'Oceania',
  'languages': {'eng': 'English', 'pih': 'Norfuk'}},
 {'name': {'common': 'Christmas Island',
   'official': 'Territory of Christmas Island',
   'nativeName': {'eng': {'official': 'Territory of Christmas Island',
     'common': 'Christmas Island'}}},
  'cca3': 'CXR',
  'currencies': {'AUD': {'name': 'Australian dollar', 'symbol': '$'}},
  'capital': ['Flying Fish Cove'],
  'region': 'Oceania',
  'languages': {'eng': 'English'}},
 {'name': {'common': 'Mongolia',
   'official': 'Mongolia',
   'nativeName': {'mon': {'official': 'Монгол улс', 'common': 'Монгол улс'}}},
  'cca3': 'MNG',
  'currencies': {'MNT': {'name': 'Mongolian tögrög', 'symbol': '₮'}},
  'capital': ['Ulan Bator'],
  'region': 'Asia',
  'languages': {'mon': 'Mongolian'}},
 {'name': {'common': 'Latvia',
   'official': 'Republic of Latvia',
   'nativeName': {'lav': {'official': 'Latvijas Republikas',
     'common': 'Latvija'}}},
  'cca3': 'LVA',
  'currencies': {'EUR': {'name': 'Euro', 'symbol': '€'}},
  'capital': ['Riga'],
  'region': 'Europe',
  'languages': {'lav': 'Latvian'}},
 {'name': {'common': 'Brunei',
   'official': 'Nation of Brunei, Abode of Peace',
   'nativeName': {'msa': {'official': 'Nation of Brunei, Abode Damai',
     'common': 'Negara Brunei Darussalam'}}},
  'cca3': 'BRN',
  'currencies': {'BND': {'name': 'Brunei dollar', 'symbol': '$'},
   'SGD': {'name': 'Singapore dollar', 'symbol': '$'}},
  'capital': ['Bandar Seri Begawan'],
  'region': 'Asia',
  'languages': {'msa': 'Malay'}},
 {'name': {'common': 'Ukraine',
   'official': 'Ukraine',
   'nativeName': {'ukr': {'official': 'Україна', 'common': 'Україна'}}},
  'cca3': 'UKR',
  'currencies': {'UAH': {'name': 'Ukrainian hryvnia', 'symbol': '₴'}},
  'capital': ['Kyiv'],
  'region': 'Europe',
  'languages': {'ukr': 'Ukrainian'}},
 {'name': {'common': 'North Korea',
   'official': "Democratic People's Republic of Korea",
   'nativeName': {'kor': {'official': '조선민주주의인민공화국', 'common': '조선'}}},
  'cca3': 'PRK',
  'currencies': {'KPW': {'name': 'North Korean won', 'symbol': '₩'}},
  'capital': ['Pyongyang'],
  'region': 'Asia',
  'languages': {'kor': 'Korean'}},
 {'name': {'common': 'Finland',
   'official': 'Republic of Finland',
   'nativeName': {'fin': {'official': 'Suomen tasavalta', 'common': 'Suomi'},
    'swe': {'official': 'Republiken Finland', 'common': 'Finland'}}},
  'cca3': 'FIN',
  'currencies': {'EUR': {'name': 'Euro', 'symbol': '€'}},
  'capital': ['Helsinki'],
  'region': 'Europe',
  'languages': {'fin': 'Finnish', 'swe': 'Swedish'}},
 {'name': {'common': 'Anguilla',
   'official': 'Anguilla',
   'nativeName': {'eng': {'official': 'Anguilla', 'common': 'Anguilla'}}},
  'cca3': 'AIA',
  'currencies': {'XCD': {'name': 'Eastern Caribbean dollar', 'symbol': '$'}},
  'capital': ['The Valley'],
  'region': 'Americas',
  'languages': {'eng': 'English'}},
 {'name': {'common': 'Azerbaijan',
   'official': 'Republic of Azerbaijan',
   'nativeName': {'aze': {'official': 'Azərbaycan Respublikası',
     'common': 'Azərbaycan'}}},
  'cca3': 'AZE',
  'currencies': {'AZN': {'name': 'Azerbaijani manat', 'symbol': '₼'}},
  'capital': ['Baku'],
  'region': 'Asia',
  'languages': {'aze': 'Azerbaijani'}},
 {'name': {'common': 'Cayman Islands',
   'official': 'Cayman Islands',
   'nativeName': {'eng': {'official': 'Cayman Islands',
     'common': 'Cayman Islands'}}},
  'cca3': 'CYM',
  'currencies': {'KYD': {'name': 'Cayman Islands dollar', 'symbol': '$'}},
  'capital': ['George Town'],
  'region': 'Americas',
  'languages': {'eng': 'English'}},
 {'name': {'common': 'Uzbekistan',
   'official': 'Republic of Uzbekistan',
   'nativeName': {'rus': {'official': 'Республика Узбекистан',
     'common': 'Узбекистан'},
    'uzb': {'official': "O'zbekiston Respublikasi", 'common': 'O‘zbekiston'}}},
  'cca3': 'UZB',
  'currencies': {'UZS': {'name': 'Uzbekistani soʻm', 'symbol': "so'm"}},
  'capital': ['Tashkent'],
  'region': 'Asia',
  'languages': {'rus': 'Russian', 'uzb': 'Uzbek'}},
 {'name': {'common': 'Ireland',
   'official': 'Republic of Ireland',
   'nativeName': {'eng': {'official': 'Republic of Ireland',
     'common': 'Ireland'},
    'gle': {'official': 'Poblacht na hÉireann', 'common': 'Éire'}}},
  'cca3': 'IRL',
  'currencies': {'EUR': {'name': 'Euro', 'symbol': '€'}},
  'capital': ['Dublin'],
  'region': 'Europe',
  'languages': {'eng': 'English', 'gle': 'Irish'}},
 {'name': {'common': 'Jersey',
   'official': 'Bailiwick of Jersey',
   'nativeName': {'eng': {'official': 'Bailiwick of Jersey',
     'common': 'Jersey'},
    'fra': {'official': 'Bailliage de Jersey', 'common': 'Jersey'},
    'nrf': {'official': 'Bailliage dé Jèrri', 'common': 'Jèrri'}}},
  'cca3': 'JEY',
  'currencies': {'GBP': {'name': 'British pound', 'symbol': '£'},
   'JEP': {'name': 'Jersey pound', 'symbol': '£'}},
  'capital': ['Saint Helier'],
  'region': 'Europe',
  'languages': {'eng': 'English', 'fra': 'French', 'nrf': 'Jèrriais'}},
 {'name': {'common': 'Rwanda',
   'official': 'Republic of Rwanda',
   'nativeName': {'eng': {'official': 'Republic of Rwanda',
     'common': 'Rwanda'},
    'fra': {'official': 'République rwandaise', 'common': 'Rwanda'},
    'kin': {'official': "Repubulika y'u Rwanda", 'common': 'Rwanda'}}},
  'cca3': 'RWA',
  'currencies': {'RWF': {'name': 'Rwandan franc', 'symbol': 'Fr'}},
  'capital': ['Kigali'],
  'region': 'Africa',
  'languages': {'eng': 'English', 'fra': 'French', 'kin': 'Kinyarwanda'}},
 {'name': {'common': 'Bosnia and Herzegovina',
   'official': 'Bosnia and Herzegovina',
   'nativeName': {'bos': {'official': 'Bosna i Hercegovina',
     'common': 'Bosna i Hercegovina'},
    'hrv': {'official': 'Bosna i Hercegovina',
     'common': 'Bosna i Hercegovina'},
    'srp': {'official': 'Босна и Херцеговина',
     'common': 'Босна и Херцеговина'}}},
  'cca3': 'BIH',
  'currencies': {'BAM': {'name': 'Bosnia and Herzegovina convertible mark',
    'symbol': 'KM'}},
  'capital': ['Sarajevo'],
  'region': 'Europe',
  'languages': {'bos': 'Bosnian', 'hrv': 'Croatian', 'srp': 'Serbian'}},
 {'name': {'common': 'Poland',
   'official': 'Republic of Poland',
   'nativeName': {'pol': {'official': 'Rzeczpospolita Polska',
     'common': 'Polska'}}},
  'cca3': 'POL',
  'currencies': {'PLN': {'name': 'Polish złoty', 'symbol': 'zł'}},
  'capital': ['Warsaw'],
  'region': 'Europe',
  'languages': {'pol': 'Polish'}},
 {'name': {'common': 'Portugal',
   'official': 'Portuguese Republic',
   'nativeName': {'por': {'official': 'República Portuguesa',
     'common': 'Portugal'}}},
  'cca3': 'PRT',
  'currencies': {'EUR': {'name': 'Euro', 'symbol': '€'}},
  'capital': ['Lisbon'],
  'region': 'Europe',
  'languages': {'por': 'Portuguese'}},
 {'name': {'common': 'Haiti',
   'official': 'Republic of Haiti',
   'nativeName': {'fra': {'official': "République d'Haïti", 'common': 'Haïti'},
    'hat': {'official': 'Repiblik Ayiti', 'common': 'Ayiti'}}},
  'cca3': 'HTI',
  'currencies': {'HTG': {'name': 'Haitian gourde', 'symbol': 'G'}},
  'capital': ['Port-au-Prince'],
  'region': 'Americas',
  'languages': {'fra': 'French', 'hat': 'Haitian Creole'}},
 {'name': {'common': 'Iran',
   'official': 'Islamic Republic of Iran',
   'nativeName': {'fas': {'official': 'جمهوری اسلامی ایران',
     'common': 'ایران'}}},
  'cca3': 'IRN',
  'currencies': {'IRR': {'name': 'Iranian rial', 'symbol': '﷼'}},
  'capital': ['Tehran'],
  'region': 'Asia',
  'languages': {'fas': 'Persian (Farsi)'}},
 {'name': {'common': 'French Southern and Antarctic Lands',
   'official': 'Territory of the French Southern and Antarctic Lands',
   'nativeName': {'fra': {'official': 'Territoire des Terres australes et antarctiques françaises',
     'common': 'Terres australes et antarctiques françaises'}}},
  'cca3': 'ATF',
  'currencies': {'EUR': {'name': 'Euro', 'symbol': '€'}},
  'capital': ['Port-aux-Français'],
  'region': 'Antarctic',
  'languages': {'fra': 'French'}},
 {'name': {'common': 'Ethiopia',
   'official': 'Federal Democratic Republic of Ethiopia',
   'nativeName': {'amh': {'official': 'የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ',
     'common': 'ኢትዮጵያ'}}},
  'cca3': 'ETH',
  'currencies': {'ETB': {'name': 'Ethiopian birr', 'symbol': 'Br'}},
  'capital': ['Addis Ababa'],
  'region': 'Africa',
  'languages': {'amh': 'Amharic'}},
 {'name': {'common': 'Kazakhstan',
   'official': 'Republic of Kazakhstan',
   'nativeName': {'kaz': {'official': 'Қазақстан Республикасы',
     'common': 'Қазақстан'},
    'rus': {'official': 'Республика Казахстан', 'common': 'Казахстан'}}},
  'cca3': 'KAZ',
  'currencies': {'KZT': {'name': 'Kazakhstani tenge', 'symbol': '₸'}},
  'capital': ['Astana'],
  'region': 'Asia',
  'languages': {'kaz': 'Kazakh', 'rus': 'Russian'}},
 {'name': {'common': 'Mali',
   'official': 'Republic of Mali',
   'nativeName': {'fra': {'official': 'République du Mali',
     'common': 'Mali'}}},
  'cca3': 'MLI',
  'currencies': {'XOF': {'name': 'West African CFA franc', 'symbol': 'Fr'}},
  'capital': ['Bamako'],
  'region': 'Africa',
  'languages': {'fra': 'French'}},
 {'name': {'common': 'Nicaragua',
   'official': 'Republic of Nicaragua',
   'nativeName': {'spa': {'official': 'República de Nicaragua',
     'common': 'Nicaragua'}}},
  'cca3': 'NIC',
  'currencies': {'NIO': {'name': 'Nicaraguan córdoba', 'symbol': 'C$'}},
  'capital': ['Managua'],
  'region': 'Americas',
  'languages': {'spa': 'Spanish'}},
 {'name': {'common': 'Germany',
   'official': 'Federal Republic of Germany',
   'nativeName': {'deu': {'official': 'Bundesrepublik Deutschland',
     'common': 'Deutschland'}}},
  'cca3': 'DEU',
  'currencies': {'EUR': {'name': 'Euro', 'symbol': '€'}},
  'capital': ['Berlin'],
  'region': 'Europe',
  'languages': {'deu': 'German'}},
 {'name': {'common': 'Estonia',
   'official': 'Republic of Estonia',
   'nativeName': {'est': {'official': 'Eesti Vabariik', 'common': 'Eesti'}}},
  'cca3': 'EST',
  'currencies': {'EUR': {'name': 'Euro', 'symbol': '€'}},
  'capital': ['Tallinn'],
  'region': 'Europe',
  'languages': {'est': 'Estonian'}},
 {'name': {'common': 'Tunisia',
   'official': 'Tunisian Republic',
   'nativeName': {'ara': {'official': 'الجمهورية التونسية',
     'common': 'تونس'}}},
  'cca3': 'TUN',
  'currencies': {'TND': {'name': 'Tunisian dinar', 'symbol': 'د.ت'}},
  'capital': ['Tunis'],
  'region': 'Africa',
  'languages': {'ara': 'Arabic'}},
 {'name': {'common': 'Saint Martin',
   'official': 'Saint Martin',
   'nativeName': {'fra': {'official': 'Saint-Martin',
     'common': 'Saint-Martin'}}},
  'cca3': 'MAF',
  'currencies': {'EUR': {'name': 'Euro', 'symbol': '€'}},
  'capital': ['Marigot'],
  'region': 'Americas',
  'languages': {'fra': 'French'}},
 {'name': {'common': 'Cameroon',
   'official': 'Republic of Cameroon',
   'nativeName': {'eng': {'official': 'Republic of Cameroon',
     'common': 'Cameroon'},
    'fra': {'official': 'République du Cameroun', 'common': 'Cameroun'}}},
  'cca3': 'CMR',
  'currencies': {'XAF': {'name': 'Central African CFA franc', 'symbol': 'Fr'}},
  'capital': ['Yaoundé'],
  'region': 'Africa',
  'languages': {'eng': 'English', 'fra': 'French'}},
 {'name': {'common': 'Micronesia',
   'official': 'Federated States of Micronesia',
   'nativeName': {'eng': {'official': 'Federated States of Micronesia',
     'common': 'Micronesia'}}},
  'cca3': 'FSM',
  'currencies': {'USD': {'name': 'United States dollar', 'symbol': '$'}},
  'capital': ['Palikir'],
  'region': 'Oceania',
  'languages': {'eng': 'English'}},
 {'name': {'common': 'Sint Maarten',
   'official': 'Sint Maarten',
   'nativeName': {'eng': {'official': 'Sint Maarten',
     'common': 'Sint Maarten'},
    'fra': {'official': 'Saint-Martin', 'common': 'Saint-Martin'},
    'nld': {'official': 'Sint Maarten', 'common': 'Sint Maarten'}}},
  'cca3': 'SXM',
  'currencies': {'ANG': {'name': 'Netherlands Antillean guilder',
    'symbol': 'ƒ'}},
  'capital': ['Philipsburg'],
  'region': 'Americas',
  'languages': {'eng': 'English', 'fra': 'French', 'nld': 'Dutch'}},
 {'name': {'common': 'Cyprus',
   'official': 'Republic of Cyprus',
   'nativeName': {'ell': {'official': 'Δημοκρατία της Κύπρος',
     'common': 'Κύπρος'},
    'tur': {'official': 'Kıbrıs Cumhuriyeti', 'common': 'Kıbrıs'}}},
  'cca3': 'CYP',
  'currencies': {'EUR': {'name': 'Euro', 'symbol': '€'}},
  'capital': ['Nicosia'],
  'region': 'Europe',
  'languages': {'ell': 'Greek', 'tur': 'Turkish'}},
 {'name': {'common': 'Morocco',
   'official': 'Kingdom of Morocco',
   'nativeName': {'ara': {'official': 'المملكة المغربية', 'common': 'المغرب'},
    'ber': {'official': 'ⵜⴰⴳⵍⴷⵉⵜ ⵏ ⵍⵎⵖⵔⵉⴱ', 'common': 'ⵍⵎⴰⵖⵔⵉⴱ'}}},
  'cca3': 'MAR',
  'currencies': {'MAD': {'name': 'Moroccan dirham', 'symbol': 'د.م.'}},
  'capital': ['Rabat'],
  'region': 'Africa',
  'languages': {'ara': 'Arabic', 'ber': 'Berber'}},
 {'name': {'common': 'Pitcairn Islands',
   'official': 'Pitcairn Group of Islands',
   'nativeName': {'eng': {'official': 'Pitcairn Group of Islands',
     'common': 'Pitcairn Islands'}}},
  'cca3': 'PCN',
  'currencies': {'NZD': {'name': 'New Zealand dollar', 'symbol': '$'}},
  'capital': ['Adamstown'],
  'region': 'Oceania',
  'languages': {'eng': 'English'}},
 {'name': {'common': 'Curaçao',
   'official': 'Country of Curaçao',
   'nativeName': {'eng': {'official': 'Country of Curaçao',
     'common': 'Curaçao'},
    'nld': {'official': 'Land Curaçao', 'common': 'Curaçao'},
    'pap': {'official': 'Pais Kòrsou', 'common': 'Pais Kòrsou'}}},
  'cca3': 'CUW',
  'currencies': {'ANG': {'name': 'Netherlands Antillean guilder',
    'symbol': 'ƒ'}},
  'capital': ['Willemstad'],
  'region': 'Americas',
  'languages': {'eng': 'English', 'nld': 'Dutch', 'pap': 'Papiamento'}},
 {'name': {'common': 'Aruba',
   'official': 'Aruba',
   'nativeName': {'nld': {'official': 'Aruba', 'common': 'Aruba'},
    'pap': {'official': 'Aruba', 'common': 'Aruba'}}},

-------------

4. Convierte los datos a un DataFrame de pandas:

* Muestra las primeras filas de DataFrame.

* Opción A

In [15]:
df_opcionA = pd.json_normalize(world_data)

df_opcionA.head(1)

,cca3,capital,region,name.common,name.official,name.nativeName.cat.official,name.nativeName.cat.common,currencies.EUR.name,currencies.EUR.symbol,languages.cat,...,name.nativeName.nfr.common,currencies.GGP.name,currencies.GGP.symbol,languages.nfr,currencies.GTQ.name,currencies.GTQ.symbol,currencies.SYP.name,currencies.SYP.symbol,currencies.TMT.name,currencies.TMT.symbol
0,AND,[Andorra la Vella],Europe,Andorra,Principality of Andorra,Principat d'Andorra,Andorra,Euro,€,Catalan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

* Opción B

In [16]:
world_data_clean = []

for country in world_data:
    capital_list = country.get("capital")

    if capital_list and len(capital_list) > 0:
        capital = capital_list[0]
    else:
        capital = "N/A"

    world_data_clean.append({
        "code": country.get("cca3"),
        "full_name": country["name"].get("official"),
        "capital": capital,
        "region": country.get("region"),
        "currency": ", ".join(
            [v["name"] for v in country.get("currencies", {}).values()]
        ),
        "language": ", ".join(
            country.get("languages", {}).values()
        )
    })

In [17]:
df_opcionB = pd.DataFrame(world_data_clean)
df_opcionB.head(1)

  code                full_name           capital  region currency language
0  AND  Principality of Andorra  Andorra la Vella  Europe     Euro  Catalan

---------------

Nivel 3
API de Open Data Barcelona

1. Utiliza la API de Open Data BCN para:

* Buscar un dataset de tu interés mediante package_search y package_show. .

In [18]:
base_url_bcn = "https://opendata-ajuntament.barcelona.cat/data/api/action"

In [19]:
search_params = {
    "q": "Bicing"
}

search_response = requests.get(f"{base_url_bcn}/package_search", params=search_params)
search_data = search_response.json()

print("Status code package_search:", search_response.status_code)
print("Número de datasets encontrados:", search_data["result"]["count"])

Status code package_search: 200
Número de datasets encontrados: 5

-------------------

2. De los resultados obtenidos, selecciona uno que tenga recursos disponibles en CSV o JSON.

In [20]:
datasets = search_data["result"]["results"]

In [ ]:
for ds in datasets:
    print(f"Dataset: {ds['name']} | Título: {ds['title']}")

Dataset: estat-estacions-bicing | Título: New Bicing stations status of Barcelona city
Dataset: informacio-estacions-bicing | Título: New Bicing stations information of the city of Barcelona
Dataset: us-del-servei-bicing | Título: Bicing service use of the city of Barcelona from August 2018 to March 2019
Dataset: cataleg-fotografies-elements-urbans-bcnroc | Título: Photographic catalogue of urban features on the Open Repository of Knowledge of the City Council of Barcelona (BCNROC)
Dataset: bicing | Título: Bicing stations, mechanical and electrical, in the city of Barcelona from August 2018 to March 2019

In [55]:
dataset_id = "us-del-servei-bicing" 

package_data = requests.get(f"{base_url_bcn}/package_show", params={"id": dataset_id}).json()

resources = package_data["result"]["resources"]

for r in resources:
    print("Recurso:", r["name"], "| Formato:", r["format"], "| ID:", r["id"])

Recurso: 2019_01_Gener_BICING_US.csv | Formato: CSV | ID: 453abff9-fb75-4f31-a699-23509bf0eca2
Recurso: 2019_01_Gener_BICING_US.7z | Formato: application/x-7z-compressed | ID: dfbd6ba7-3cbe-49f0-aa3c-ce96a3194cfc
Recurso: 2019_02_Febrer_BICING_US.csv | Formato: CSV | ID: 8cd14603-4a48-4425-9683-4ac5b94faea6
Recurso: 2019_02_Febrer_BICING_US.7z | Formato: application/x-7z-compressed | ID: c994f528-da65-47f6-a3e1-8667ea7ffe3e
Recurso: 2019_03_Marc_BICING_US.csv | Formato: CSV | ID: fd15ed46-9b4b-4af9-a9bb-25daf62a7f0c
Recurso: 2019_03_Marc_BICING_US.7z | Formato: application/x-7z-compressed | ID: 5b69aba7-296b-4ebe-954b-5604ba0c86e3
Recurso: 2018_08_Agost_BICING_US.csv | Formato: CSV | ID: 38c94f78-07a8-40d9-b7b5-d9a9574b8ae9
Recurso: 2018_08_Agost_BICING_US.7z | Formato: application/x-7z-compressed | ID: 32b5819c-987d-47bb-8724-2eb2228957c9
Recurso: 2018_09_Setembre_BICING_US.csv | Formato: CSV | ID: 727981d3-3038-4aa7-81b4-b47a35f99f37
Recurso: 2018_09_Setembre_BICING_US.7z | Formato: application/x-7z-compressed | ID: 7b116c3c-4442-41d8-b4f1-0311a95a38d9
Recurso: 2018_10_Octubre_BICING_US.csv | Formato: CSV | ID: 9c507837-598a-4433-b027-a9aa5138f1f7
Recurso: 2018_10_Octubre_BICING_US.7z | Formato: application/x-7z-compressed | ID: f990113e-b362-478a-9d8c-53ad26c059fb
Recurso: 2018_11_Novembre_BICING_US.csv | Formato: CSV | ID: 6d35ca24-03f3-4a7c-b3fc-d46df3280302
Recurso: 2018_11_Novembre_BICING_US.7z | Formato: application/x-7z-compressed | ID: 51302366-b8d2-485c-ac3d-32f983365a4a
Recurso: 2018_12_Desembre_BICING_US.csv | Formato: CSV | ID: fc52c8b5-23bd-493e-8f47-a0da50983b0f
Recurso: 2018_12_Desembre_BICING_US.7z | Formato: application/x-7z-compressed | ID: 4c22bc8a-81ef-404b-a3f6-7262bcac94b8

In [57]:
recurso_tiempo_real = next(
    r for r in resources if r["format"] == "CSV"
)

print(f"Nombre: {recurso_tiempo_real['name']}")
print(f"URL de descarga: {recurso_tiempo_real['url']}")

Nombre: 2019_01_Gener_BICING_US.csv
URL de descarga: https://opendata-ajuntament.barcelona.cat/data/dataset/4a469cf6-dbab-4aa1-b492-aa0af9af93c9/resource/453abff9-fb75-4f31-a699-23509bf0eca2/download

--------------

3. Con el resource_id del recurso seleccionado, realiza una consulta mediante datastore_search por:

* Recuperar al menos 100 registros.

In [ ]:
datastore_data = response_datastore.json()
estaciones = datastore_data["result"]["records"]

if estaciones:
    print("Columnas disponibles:", estaciones[0].keys())

Columnas disponibles: dict_keys(['electricalBikesInUsage', 'bikesInUsage', 'dateTime', 'mechanicalBikesInUsage', 'error', '_id'])

In [ ]:
resource_id = "453abff9-fb75-4f31-a699-23509bf0eca2"

------------

4. Convierte los resultados a un DataFrame.

In [ ]:
params = {
    "resource_id": "453abff9-fb75-4f31-a699-23509bf0eca2",
    "limit": 100
}

response = requests.get(f"{base_url_bcn}/datastore_search", params=params)
data = response.json()

df = pd.DataFrame(data["result"]["records"])

df

------------

5. Guarda DataFrame en un archivo .csv.

In [64]:
df.to_csv("uso_bicing.csv", index=False)

print("Archivo guardado con éxito.")

Archivo guardado con éxito.

--------------